openapi: 3.0.3
info:
  title: AI Character and Media Streaming API
  description: API for managing AI characters and streaming media content
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/ai-characters:
    get:
      summary: Get paginated list of AI characters
      parameters:
        - name: page
          in: query
          description: Page number (starting from 1)
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: A paginated list of AI characters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResponse'
        '400':
          description: Invalid pagination parameters
          content:
            text/plain:
              example: "Invalid page number"
        '500':
          description: Internal server error
          content:
            text/plain:
              example: "Internal Server Error"

  /stream/{filePath}:
    get:
      summary: Stream HLS media files
      parameters:
        - name: filePath
          in: path
          required: true
          description: Path to the HLS file (e.g., "wangling.m3u8")
          schema:
            type: string
            pattern: ^[\w\-\/]+\.(m3u8|ts)$
      responses:
        '200':
          description: Media file content
          content:
            application/x-mpegURL:
              schema:
                type: string
                format: binary
            video/MP2T:
              schema:
                type: string
                format: binary
        '404':
          description: File not found
          content:
            text/plain:
              example: "404 page not found"
components:
  schemas:
    AICharacter:
      type: object
      required:
        - id
        - name
        - imageUrl
        - createdAt
      properties:
        id:
          type: integer
          description: Unique identifier
        name:
          type: string
          description: Name of the AI character
        imageUrl:
          type: string
          description: URL to the character's image
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp

    PaginatedResponse:
      type: object
      required:
        - data
        - page
        - limit
        - total_pages
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AICharacter'
        page:
          type: integer
          description: Current page number
        limit:
          type: integer
          description: Items per page
        total_pages:
          type: integer
          description: Total number of pages
